export const NAME = 'Name';
export const DESCRIPTION = 'Description';
export const CREATE = 'Create';
export const NAME_CONTROL = 'name';
export const DESCRIPTION_CONTROL = 'description';
export const NAME_REQUIRED_ERROR = 'The name is required.';
export const NAME_MAXLENGTH_ERROR = 'The name cannot exceed 50 characters.';
export const DESCRIPTION_REQUIRED_ERROR = 'The description is required.';
export const DESCRIPTION_MAXLENGTH_ERROR = 'The description cannot exceed 120 characters.';
